### ISSUE TITLE
Export TQ

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord-box3/tn-converter-app#69]
The export should produce a TSV file conforming to the TQ TSV standard: https://forum.door43.org/t/parascriptural-tab-separated-value-format-specification-v2/870

Examples of a TQs in the new TSV format can be found here: https://git.door43.org/unfoldingWord/en_tq/src/branch/newFormat

**Comment by birchamp** [comment]
@mannycolon just a heads up that I added this issue for QA.

**Comment by mannycolon** [comment]
@birchamp Should we add the specs for TN as well?

**Comment by cckozie** [comment]
The same problems exist for both tN and tQ projects

Problem 1.
The export file does not conform to the tsv spec in that there are rows in which the ID field is empty.

Problem 2.
In some cases dragging rows results in empty rows in the exported file. (I'm assuming we don't want empty rows since tC Create doesn't handle them well, and I expect tC won't like them much either.)

This is the project as loaded:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/751ebc2c-47a0-475b-bb22-95c513e67f86)

This is the project after dragging the last 1:6 row to the first 1:7 row:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/672d543b-b42d-4880-ae5f-0b6852ce3ce7)

This is the relevant portion of the exported file:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/b83fd26c-4792-4c60-8ea6-4a74a19d0f21)

**Comment by elsylambert** [comment]
The problems 1 and 2 are no longer found in the Exported TQ in the beta version. The empty rows are not found and all the rows have Id.
