### ISSUE TITLE
Performance problems 

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-box3/tn-converter-app#91]
Timings were made on my fastest Mac. On my faster Windows machine the performance is improved about 15%.
1. Opening a new Luke es-419 tN project takes about 5 minutes. During about 4 of those minutes there is no indication of processing, or that the app has not locked up.
2. When dragging and dropping a row, it takes about 1 minute before the row shows up in the new position. There is no indication of processing during that time. (It takes about 45 seconds for this action in the beta (tN only) version.
3. When clicking the Included checkbox, it takes about 45 seconds for the checkbox state to change.
4. When clicking the checkbox to show an additional column, it takes about 1 minute for that change to be displayed.
5. During these time lapses the "Page Unresponsive" alert is often displayed, sometimes it is displayed many times while waiting.
6. If the "Exit Page" option is taken on that alert, when logging back in it takes almost 4 minutes after clicking the Login button for the next page to appear. That next page is briefly the Luke project, then the user is taken to the "My Projects" page. When the Luke project is selected, it takes almost 4 minutes for the project to be opened. (I had to click the "Wait" button on the alert at least 6 times when waiting for the project to load.
7. There is no indication of processing during the time to process items 2-6.
8. Somtimes while waiting for the desired event to happen the user is kicked out to this page:
![Screen Shot 2021-04-24 at 8.28.41 AM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/6088a30e-2e39-441a-8403-a9a76842e23d)

**Comment by elsylambert** [comment]
https://deploy-preview-95--tn-converter-app.netlify.app/
@mannycolon Here are some problems that I encountered when testing this issue:
1. Login is failing with very slow response and no indication to the user when "Keep me logged in " checkbox is not checked.
![Screen Shot 2021-07-06 at 11.58.46 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/14f9b7be-0aaf-4cee-b1b1-e7a969bfa78e)
2. Login is delayed even when the "Keep me logged in " checkbox is checked.
![Screen Shot 2021-07-06 at 12.01.42 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/665ae67d-7dec-4cfb-a52f-517554fdc1b6)
3. After a long wait, I see the Search Repo page when I search using my username, I can see the console with Fail messages but nothing on the page. Apps seems to be hung.
![Screen Shot 2021-07-06 at 11.57.55 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/43c7557b-9dbd-46fa-b98b-55672479a83f)

Note: The above problem could be because of cache. When I opened the preview build in incognito window, it seems to work fine and load the page faster.

**Comment by elsylambert** [comment]
@mannycolon wrote up  separately #96, #97, #98 while testing this issue.

**Comment by mannycolon** [comment]
@elsylambert The server issues above are related to problems on DCS/Gitea, not the app. Rich is working hard trying to address the problem.

**Comment by elsylambert** [comment]
The latest build on July 14, 2021 addresses major performance issues.
- Opening a file is faster for e.g. Luke tN project takes about 45 seconds as oppose to 5 minutes.
- Dragging and dropping taking 1 second.
- Checking/unchecking "Include" checkbox works instantly.
- Not seeing "Page unresponsive".
